name: Secrets workflow 
on: 
  push: 
    branches:
      - main

jobs:
  setup-system: 
    name: 'setup'
    runs-on: ubuntu-latest
    steps:
    - name: Install system dependencies
      run:
        sudo apt-get update
        sudo apt-get install -y make

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Set up Python virtual environment and instal dependencies
      run:
        make requirements

    - name: Run full code quality, test and coverage checks
      run:
        make run-checks

    # - name: Archive coverage report
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: coverage-report
    #     path: coverage.txt

  deploy-dev:
    # only runs if push or pull request happens to main branch
    if: github.ref == 'refs/heads/main'
    name: deploy-dev
    environment: dev
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Install system dependencies
        run:
          sudo apt-get update
          sudo apt-get install -y make
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: S{{ secrets.AWS_REGION }}
      - name: Install Terraform
        uses: hasicorp/setup-terraform@v3
      - name: Terraform Init
        working-directory: terraform
        run: terraform init
      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan
      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve

    